# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Medots < Formula
  desc ""
  homepage "https://github.com/aminehmida/medots"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aminehmida/medots/releases/download/v0.1.6/medots_0.1.6_Darwin_x86_64.tar.gz"
      sha256 "c994e34134c00c23fa7d2ac6339f2620098d688bff82eb4f4c3d5d02ebc63a83"

      def install
        bin.install "medots"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aminehmida/medots/releases/download/v0.1.6/medots_0.1.6_Darwin_arm64.tar.gz"
      sha256 "d012b1c9e28eeffee5a484a5ab0f02c320181b708c7c85bd8f343fc2653bf57e"

      def install
        bin.install "medots"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aminehmida/medots/releases/download/v0.1.6/medots_0.1.6_Linux_x86_64.tar.gz"
      sha256 "0e234faa75a450f7a312620cf1ec964288d211e7f27189529417820a683d5dae"

      def install
        bin.install "medots"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aminehmida/medots/releases/download/v0.1.6/medots_0.1.6_Linux_arm64.tar.gz"
      sha256 "bc5d89e6d607026843b2c89fcb44c148e76430b3b1a676f487c42fc0a2c602fc"

      def install
        bin.install "medots"
      end
    end
  end
end
