# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Medots < Formula
  desc ""
  homepage "https://github.com/aminehmida/medots"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aminehmida/medots/releases/download/v0.1.7/medots_0.1.7_Darwin_arm64.tar.gz"
      sha256 "05ce0b66e31343f7087ff7b422461eb03ac8ad42d7250dd57007c6e0a941cc48"

      def install
        bin.install "medots"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aminehmida/medots/releases/download/v0.1.7/medots_0.1.7_Darwin_x86_64.tar.gz"
      sha256 "87530ac0f5d5d0c827e7dd7afdf960ab07821a198b5406c68730efe47ca1414e"

      def install
        bin.install "medots"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aminehmida/medots/releases/download/v0.1.7/medots_0.1.7_Linux_x86_64.tar.gz"
      sha256 "182bb57b24075afb6aaa208a3f32f0a909119b26b0bec4fd5536c3b233b6a753"

      def install
        bin.install "medots"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aminehmida/medots/releases/download/v0.1.7/medots_0.1.7_Linux_arm64.tar.gz"
      sha256 "43930a732272341a0863e677353a5fc374c4d1930c4e77a1d8ce5f921fb246b2"

      def install
        bin.install "medots"
      end
    end
  end
end
